import { jsPDF } from "jspdf";
import { AnalysisResults } from "../types";

export async function createPDFReport(
  analysis: AnalysisResults
): Promise<Buffer> {
  try {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    let yPos = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - 2 * margin;

    // Header
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("Karen's Official Roast Report", pageWidth / 2, yPos, {
      align: "center",
    });
    yPos += 15;

    // Overall score
    doc.setFontSize(18);
    doc.text(
      `Overall Score: ${analysis.overall_rating}/10`,
      pageWidth / 2,
      yPos,
      {
        align: "center",
      }
    );
    yPos += 15;

    // Summary section
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Summary", margin, yPos);
    yPos += 8;

    doc.setFontSize(11);
    doc.setFont("helvetica", "italic");
    const summaryLines = doc.splitTextToSize(
      analysis.roast_summary,
      contentWidth
    );
    doc.text(summaryLines, margin, yPos);
    yPos += summaryLines.length * 5 + 10;

    // Design Flaws section
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(`Design Flaws (${analysis.design_flaws.length})`, margin, yPos);
    yPos += 10;

    analysis.design_flaws.forEach((flaw, index) => {
      // Check if we need a new page
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }

      // Flaw number and issue
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 0, 0);
      const issueLines = doc.splitTextToSize(
        `${index + 1}. ${flaw.issue}`,
        contentWidth
      );
      doc.text(issueLines, margin, yPos);
      yPos += issueLines.length * 5 + 3;

      // Severity badge
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.setFont("helvetica", "normal");
      doc.text(`Severity: ${flaw.severity.toUpperCase()}`, margin + 5, yPos);
      yPos += 6;

      // Roast
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      doc.setFont("helvetica", "italic");
      const roastLines = doc.splitTextToSize(
        `"${flaw.roast}"`,
        contentWidth - 5
      );
      doc.text(roastLines, margin + 5, yPos);
      yPos += roastLines.length * 5 + 3;

      // Recommendation
      if (flaw.recommendation) {
        doc.setFont("helvetica", "normal");
        doc.setTextColor(0, 119, 0);
        const recLines = doc.splitTextToSize(
          `Fix: ${flaw.recommendation}`,
          contentWidth - 5
        );
        doc.text(recLines, margin + 5, yPos);
        yPos += recLines.length * 5 + 5;
      }

      yPos += 5;
    });

    // Positive aspects (if any)
    if (analysis.positive_aspects && analysis.positive_aspects.length > 0) {
      // Check if we need a new page
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }

      yPos += 10;
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 0, 0);
      doc.text("What Didn't Make Karen Gag", margin, yPos);
      yPos += 10;

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(0, 102, 0);

      analysis.positive_aspects.forEach((positive) => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }
        const positiveLines = doc.splitTextToSize(
          `• ${positive}`,
          contentWidth
        );
        doc.text(positiveLines, margin, yPos);
        yPos += positiveLines.length * 5 + 3;
      });
    }

    // Footer on last page
    const pageCount = doc.getNumberOfPages();
    doc.setPage(pageCount);
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by Karen's WebHouse", pageWidth / 2, 280, {
      align: "center",
    });
    doc.text(
      "Because your website needed an intervention.",
      pageWidth / 2,
      285,
      {
        align: "center",
      }
    );

    // Convert to Buffer
    const pdfBuffer = Buffer.from(doc.output("arraybuffer"));
    return pdfBuffer;
  } catch (error) {
    console.error("Error creating PDF:", error);
    throw error;
  }
}
